# Generated by Django 2.2.7 on 2019-11-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.TextField(max_length=20)),
                ('pswd', models.TextField(max_length=20)),
            ],
        ),
    ]
