# Generated by Django 2.2.7 on 2019-11-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testlogin', '0002_auto_20191109_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='log',
            new_name='logclass',
        ),
    ]
